/** Stats Actions types  */
export const GET_STATS_LOADING = 'GET_STATS_LOADING';
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS';
export const GET_STATS_FAILED = 'GET_STATS_FAILED';

export const GET_COVERAGE_CAT_LOADING = 'GET_COVERAGE_CAT_LOADING';
export const GET_COVERGAE_CAT_SUCCESS = 'GET_COVERAGE_CAT_SUCCESS';
export const GET_COVERAGE_CAT_FAILED = 'GET_COVERAGE_CAT_FAILED';

export const GET_DOWNLOAD_FILE_LOADING = 'GET_DOWNLOAD_FILE_LOADING';
export const GET_DOWNLOAD_FILE_SUCCESS = 'GET_DOWNLOAD_FILE_SUCCESS';
export const GET_DOWNLOAD_FILE_FAILED = 'GET_DOWNLOAD_FILE_FAILED';

export const UPLOAD_FILE_LOADING = 'UPLOAD_FILE_LOADING';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED';

export const HIDE_UPLOAD_FILE_STATUS_MODAL = 'HIDE_UPLOAD_FILE_STATUS_MODAL';

export const GET_DATA_DETAIL_SUCCESS = 'GET_DATA_DETAIL_SUCCESS';
export const GET_DATA_DETAIL_LOADING = 'GET_DATA_DETAIL_LOADING';
export const GET_DATA_DETAIL_FAILED = 'GET_DATA_DETAIL_FAILED';

export const GET_DETAIL_MONTH_DATA_SUCCESS = 'GET_DETAIL_MONTH_DATA_SUCCESS';
export const GET_DETAIL_MONTH_DATA_LOADING = 'GET_DETAIL_MONTH_DATA_LOADING';
export const GET_DETAIL_MONTH_DATA_FAILED = 'GET_DETAIL_MONTH_DATA_FAILED';

export const SEARCH_CLIENT_LOADING = 'SEARCH_CLIENT_LOADING';
export const SEARCH_CLIENT_FAILED = 'SEARCH_CLIENT_FAILED';
export const SEARCH_CLIENT_SUCCESS = 'SEARCH_CLIENT_SUCCESS';


export const GET_FILE_STATUS_LOADING = 'GET_FILE_STATUS_LOADING';
export const GET_FILE_STATUS_FAILED = 'GET_FILE_STATUS_FAILED';
export const GET_FILE_STATUS_SUCCESS = 'GET_FILE_STATUS_SUCCESS';


export const UPLOAD_FILE_S3_LOADING = 'UPLOAD_FILE_S3_LOADING';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
export const CLEAN_INFO_CLIENT = 'CLEAN_INFO_CLIENT';

export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';

export const SET_USER_INFO = 'SET_USER_INFO';
