// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:74da32ec-1e3b-4b9b-84d4-2c5687919343",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aPcGMnUdk",
    "aws_user_pools_web_client_id": "3u4de5ukca2adm28g380di8589",
    "oauth": {},
    "aws_content_delivery_bucket": "cabere-system-prod",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1fj1rci29ld6k.cloudfront.net",
    "aws_appsync_graphqlEndpoint": "https://ikikuwuc6fbpvjeboo62w44d4q.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;